<a href="https://colab.research.google.com/github/Sourish168/Python/blob/main/PyTorch/PyTorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction and Installation
- From https://pytorch.org/ we can download the required package of PyTorch in our machine(Linux/Mac/Windows).
- If gpu is available then the cuda version is preferable for NVIDIA GPUs only.
- In local mechine we have to create a virtual environment and install the appropiate version of python.
- In Google Colab we have to install PyTorch by "!pip install torch" command.
- By "torch.cuda.is_available()" we can check if the cuda is there or not.

In [1]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [2]:
import torch
torch.cuda.is_available() # False means there is no cuda in the machine

False

## Tensor Basics
- In NumPy we have used vectors, matrices, tensors. In PyTorch everything starts with tensors i.e. 1D, 2D, nD arrays.

In [3]:
import torch
x = torch.empty(1) # Scalar
print(x)

tensor([2.8665e+32])


In [4]:
x = torch.empty(2, 3, 4) # 3D array
print(x)

tensor([[[ 5.7344e-30,  4.4355e-41,  5.7344e-30,  4.4355e-41],
         [        nan,  0.0000e+00,  1.8728e+31,  1.4153e-43],
         [ 3.2892e+14,  4.4354e-41,  0.0000e+00,  0.0000e+00]],

        [[ 8.9683e-44,  0.0000e+00,  2.6905e-43,  0.0000e+00],
         [-6.3723e+09,  4.4354e-41,  0.0000e+00,  1.4013e-45],
         [ 9.2327e-26,  3.2695e-41,  0.0000e+00,  0.0000e+00]]])


In [5]:
x = torch.zeros(2, 2, 3) # 3D array of zeros
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
