## Creating an Array using NumPy
- Using NumPy we can create n-dimensional arrays.
- We can input the values of the array from the user and make the numpy array.

In [1]:
import numpy as np
a = [1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
a = []
n = int(input("Enter the size of an array: "))
for i in range(n):
    val = int(input(f"Enter input number {i+1}: "))
    a.append(val)
arr = np.array(a)
print("\nThe created array is:", arr)


The created array is: [11 23 65 20 44]


## Creating Higher Dimensional Arrays using NumPy

In [6]:
import numpy as np
a = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.ndim # Checking the dimension of the array

2

In [8]:
arr.shape # Checking the shape of the array

(3, 3)