## NumPy Built-in Functions
- Special Functions, that can easily implemented by NumPy.
- E.g. numpy.zeros, numpy.ones, numpy.eye, numpy.random etc.

In [1]:
import numpy as np
a = np.zeros(4) # Creating an one dimensional array of zeros
b = np.zeros((3, 4)) # Creating a two dimensional array of zeros
c = np.zeros((3, 4, 2)) # Creating a three dimensional array of zeros
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [0. 0. 0. 0.]

Array b:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array c:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [2]:
a = np.ones(4) # Creating an one dimensional array of ones
b = np.ones((3, 4)) # Creating a two dimensional array of ones
c = np.ones((3, 4, 2)) # Creating a three dimensional array of ones
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [1. 1. 1. 1.]

Array b:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array c:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [3]:
a = np.eye(3) # Creating an identity matrix
b = np.eye(3, 4) # Creating a matrix with ones on the diagonal
c = np.eye(3, 4, 1) # Creating a matrix with ones on the diagonal with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array b:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Array c:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
a = np.diag([1, 2, 3, 4]) # Creating a diagonal matrix
b = np.diag(a) # Extracting the diagonal elements of a matrix
c = np.diag(a, 1) # Extracting the diagonal elements of a matrix with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Array b:
 [1 2 3 4]

Array c:
 [0 0 0]


In [5]:
a = np.random.randint(1, 10, 3) # Creating an array of random integers
print("Array a:\n", a) # Generating 3 random integers from [1, 10)
b = np.random.randint(1, 10, (3, 4)) # Creating a 2D array of random integers
print("\nArray b:\n", b) # Generating 3x4 random integers from [1, 10)

Array a:
 [9 1 3]

Array b:
 [[4 8 7 2]
 [7 4 8 6]
 [5 8 6 4]]


In [6]:
a = np.random.rand(5) # Creating an array of random floats
print("Array a:\n", a) # Generating 5 random floats from [0, 1)
b = np.random.rand(2, 3) # Creating a 2D array of random floats
print("\nArray b:\n", b) # Generating 2x3 random floats from [0, 1)

Array a:
 [0.19352342 0.86609126 0.83663857 0.24512949 0.35117626]

Array b:
 [[0.98397677 0.28575315 0.30274071]
 [0.51678141 0.80579931 0.47502927]]


In [7]:
a = np.random.randn(5) # Creating an array of random floats from Normal Distribution
print("Array a:\n", a) # Generating 5 random floats from N(0, 1)
b = np.random.randn(2, 3) # Creating a 2D array of random floats from Normal Distribution
print("\nArray b:\n", b) # Generating 2x3 random floats from N(0, 1)

Array a:
 [ 0.08575089 -0.50800939 -0.2529933  -0.87146088  0.05838016]

Array b:
 [[ 0.44061252 -1.17566646 -1.02456364]
 [ 0.71260893 -0.48998469 -0.19192676]]
