## Indexing & Slicing of NumPy Array
- To get any values from a NumPy array we can use indexing and slicing method.
- Always remember indexing in python starts from 0 upto n-1, where n = lenth of the array.
- For a n-dimensional array, we have to mention n different indexes, not more than that.
- In some cases less number of indexing by default considers the first m indexes of the array (m<n).
- We can use negetive indexing and slicing. Rule: index(n-k) = index(-k)

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"The {i} indexed element is:", a[i]) # 1D array indexing

Array a:
 [1 2 3 4 5 6 7 8 9] 

The 0 indexed element is: 1
The 1 indexed element is: 2
The 2 indexed element is: 3
The 3 indexed element is: 4
The 4 indexed element is: 5
The 5 indexed element is: 6
The 6 indexed element is: 7
The 7 indexed element is: 8
The 8 indexed element is: 9


In [2]:
a = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]]) # 2D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"The {i} indexed element is:", a[i]) # 1D array indexing but for each index it is giving a 1D array

Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

The 0 indexed element is: [1 2 3]
The 1 indexed element is: [4 5 6]
The 2 indexed element is: [7 8 9]


In [3]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"\nThe {i} indexed element is:\n", a[i]) # 1D array indexing but for each index it is giving a 2D array

for i in range(len(a)):
    for j in range(len(a[i])):
        print(f"\nThe ({i}, {j}) indexed element is:\n", a[i][j]) # 2D array indexing but for each index it is giving a 1D array

Array a:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] 


The 0 indexed element is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

The 1 indexed element is:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

The 2 indexed element is:
 [[21 22 23]
 [24 25 26]
 [27 28 29]]

The (0, 0) indexed element is:
 [1 2 3]

The (0, 1) indexed element is:
 [4 5 6]

The (0, 2) indexed element is:
 [7 8 9]

The (1, 0) indexed element is:
 [11 12 13]

The (1, 1) indexed element is:
 [14 15 16]

The (1, 2) indexed element is:
 [17 18 19]

The (2, 0) indexed element is:
 [21 22 23]

The (2, 1) indexed element is:
 [24 25 26]

The (2, 2) indexed element is:
 [27 28 29]


In [4]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

print("The (0, 1, 2) indexed element of a is:", a[0, 1, 2]) # Indexing a 3D array
print("The (2, 1, 0) indexed element of a is:", a[2, 1, 0]) # Indexing a 3D array

print(a[1, 0, 2] == a[1][0][2]) # Checking if both are same, another way of indexing
print(a[1, 0] == a[1][0]) # Checking if both are same, another way of indexing
print(a[1] == a[1][0][2]) # Checking if both are same, another way of indexing
# For the 2nd and 3rd case it is checking element wise equality for both the arrays

The (0, 1, 2) indexed element of a is: 6
The (2, 1, 0) indexed element of a is: 24
True
[ True  True  True]
[[False False  True]
 [False False False]
 [False False False]]


In [5]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1D array
print("The slicing of b from 3rd index to 7th index is:", b[3:8])
print("\nThe slicing of a from 3rd index to 7th index is:\n", a[3:8]) # Since the index are empty
print("\nThe slicing of b from 0th index to 2nd index is:\n", a[0:2])

The slicing of b from 3rd index to 7th index is: [4 5 6 7 8]

The slicing of a from 3rd index to 7th index is:
 []

The slicing of b from 0th index to 2nd index is:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [6]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
print("a[1:] =\n", a[1:]) # Returns every element after and including 1
print("\na[:2] =\n", a[:2]) # Returns every element before 2 (excluding 2)
print("\na[1:, 1:] =\n", a[1:, 1:]) # Returns every element after and including [1, 1]
print("\na[:2, :2] =\n", a[:2, :2]) # Returns every element before [2, 2] (excluding [2, 2])

a[1:] =
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

a[:2] =
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

a[1:, 1:] =
 [[[14 15 16]
  [17 18 19]]

 [[24 25 26]
  [27 28 29]]]

a[:2, :2] =
 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [7]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

a[0:2, -1] == a[0:2, 2] # Checking if both are same, index(n-k) = index(-k), here k=1, n=3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [8]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

print("a[0:2] =\n", a[0:2])
print("\na[1:3] =\n", a[1:3])
print("\nSum of the above array slices is:\n", a[0:2]+a[1:3])
print("\nLet's divide the array sum by 2:\n", (a[0:2]+a[1:3])/2) # Note there is float value now
print("\nLet's divide the array sum by 8:\n", (a[0:2]+a[1:3])/8) # The float is clear now
print("\nLet's now convert the final array into integer array:")
np.array((a[0:2]+a[1:3])/8, dtype = np.int64)

a[0:2] =
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

a[1:3] =
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

Sum of the above array slices is:
 [[[12 14 16]
  [18 20 22]
  [24 26 28]]

 [[32 34 36]
  [38 40 42]
  [44 46 48]]]

Let's divide the array sum by 2:
 [[[ 6.  7.  8.]
  [ 9. 10. 11.]
  [12. 13. 14.]]

 [[16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]]]

Let's divide the array sum by 8:
 [[[1.5  1.75 2.  ]
  [2.25 2.5  2.75]
  [3.   3.25 3.5 ]]

 [[4.   4.25 4.5 ]
  [4.75 5.   5.25]
  [5.5  5.75 6.  ]]]

Let's now convert the final array into integer array:


array([[[1, 1, 2],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 5, 5],
        [5, 5, 6]]])