## Reshaping of Array
- We can reshape an array as required.
- But always remember that original array shape and reshaping array shape should be matching, or there is an error.

In [1]:
import numpy as np
a = np.random.randint(0, 99, (4, 3))
a

array([[82, 45,  3],
       [30, 70, 19],
       [75, 91, 88],
       [34, 61, 68]])

In [2]:
a.shape # Total 12 elements are there

(4, 3)

In [3]:
a.reshape(2, 6) # 2 rows and 6 columns, 12 elements

array([[82, 45,  3, 30, 70, 19],
       [75, 91, 88, 34, 61, 68]])

In [4]:
a.reshape(3, 4) # 3 rows and 4 columns, 12 elements

array([[82, 45,  3, 30],
       [70, 19, 75, 91],
       [88, 34, 61, 68]])

In [5]:
a.reshape(2, 3, 2) # 3D array

array([[[82, 45],
        [ 3, 30],
        [70, 19]],

       [[75, 91],
        [88, 34],
        [61, 68]]])

In [6]:
a.reshape(2, 1, 2, 3) # 4D array

array([[[[82, 45,  3],
         [30, 70, 19]]],


       [[[75, 91, 88],
         [34, 61, 68]]]])

In [7]:
a.reshape(1, 12) # 2D array

array([[82, 45,  3, 30, 70, 19, 75, 91, 88, 34, 61, 68]])

In [8]:
a.reshape(12) # 1D array

array([82, 45,  3, 30, 70, 19, 75, 91, 88, 34, 61, 68])

In [9]:
a.reshape(2, 7) # 2 rows and 7 columns, 14 elements, not 12 elements, gives error

ValueError: cannot reshape array of size 12 into shape (2,7)

In [10]:
a # The actual array is not changing

array([[82, 45,  3],
       [30, 70, 19],
       [75, 91, 88],
       [34, 61, 68]])

In [11]:
a = a.reshape(2, 2, 3) # To change the actual array
a

array([[[82, 45,  3],
        [30, 70, 19]],

       [[75, 91, 88],
        [34, 61, 68]]])

In [12]:
a.reshape(-1, 6) # Only assigning the column value

array([[82, 45,  3, 30, 70, 19],
       [75, 91, 88, 34, 61, 68]])

In [13]:
a.reshape(6, -1) # Only assigning the row value

array([[82, 45],
       [ 3, 30],
       [70, 19],
       [75, 91],
       [88, 34],
       [61, 68]])

In [14]:
a.reshape(2, 2, -1) # Only assigning the row and column

array([[[82, 45,  3],
        [30, 70, 19]],

       [[75, 91, 88],
        [34, 61, 68]]])

In [15]:
a.reshape(-4, 4) # Only assigning the column value

array([[82, 45,  3, 30],
       [70, 19, 75, 91],
       [88, 34, 61, 68]])

In [16]:
a.reshape(0, 12) # Since 0 cannot be a dimension

ValueError: cannot reshape array of size 12 into shape (0,12)