## NumPy Seed Function
- Used for many important purpose where we need to fix our randomly generated array.
- The pseudo number generator gives us the same output for a particular seed number.

In [1]:
import numpy as np
np.random.seed(10)
arr = np.random.randint(0, 100, 10)
arr # Seed always comes with Random number

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [2]:
np.random.seed(10)
arr = np.random.randint(0, 100, 10)
arr # Note the same random number is generated

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [3]:
np.random.seed(10)
arr = np.random.randint(0, 50, 10)
arr # Seed is same but the variation in range or dimension can change the array

array([ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29])

In [4]:
arr.size # Checking the size of the array

10