## Conditional Selection in NumPy Array
- We can use logical symbols for conditioning. E.g. logical or, logical and etc.
- We can update an array using conditional selection rule.

In [1]:
import numpy as np
a = np.arange(1, 15) # Arranging array elements starting from 1 to 14
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
a > 7 # Elementwise condition checking, creating binary array

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True])

In [3]:
a = np.arange(1, 15, 2) # Arranging array elements starting from 1 to 14 with gap 2
print("a =", a)
b = a >= 7 # Conditional selection
print("\nb =", b)
print("\na[b] =", a[b]) # Binary Indexing for retriving elements

a = [ 1  3  5  7  9 11 13]

b = [False False False  True  True  True  True]

a[b] = [ 7  9 11 13]


In [4]:
a = np.arange(0, 15)
print("a =", a, "\n")
a[a%2 == 0] # Conditional selection

a = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 



array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [5]:
print("a == 10:\n", a == 10, "\n") # == is logical equal
a[a == 10] # Conditional selection

a == 10:
 [False False False False False False False False False False  True False
 False False False] 



array([10])

In [6]:
print("(a > 5) & (a < 10):\n", (a > 5) & (a < 10), "\n") # & is logical and
a[(a > 5) & (a < 10)] # Conditional selection

(a > 5) & (a < 10):
 [False False False False False False  True  True  True  True False False
 False False False] 



array([6, 7, 8, 9])

In [7]:
print("(a < 5) & (a > 10):\n", (a < 5) & (a > 10), "\n")
a[(a < 5) & (a > 10)] # Conditional selection, everything is false, thus null array

(a < 5) & (a > 10):
 [False False False False False False False False False False False False
 False False False] 



array([], dtype=int64)

In [8]:
print("(a < 5) | (a > 10):\n", (a < 5) | (a > 10), "\n") # | is logical or
a[(a < 5) | (a > 10)] # Conditional selection

(a < 5) | (a > 10):
 [ True  True  True  True  True False False False False False False  True
  True  True  True] 



array([ 0,  1,  2,  3,  4, 11, 12, 13, 14])

In [9]:
a[a%2 == 0] = 0 # Conditional update
a # Replacing 0 for all True values

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])

In [10]:
a = np.arange(1, 25).reshape(3, 4, 2)
a[(a%2 == 0) | (a%5 == 1)] = 0 # All even and 1, 11, 21 are in True position
a

array([[[ 0,  0],
        [ 3,  0],
        [ 5,  0],
        [ 7,  0]],

       [[ 9,  0],
        [ 0,  0],
        [13,  0],
        [15,  0]],

       [[17,  0],
        [19,  0],
        [ 0,  0],
        [23,  0]]])