## Various Operations on NumPy Array
- There are various operations in NumPy  array which are not our usual operations.

In [1]:
import numpy as np
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [2]:
a+2 # Adding 2 to each element

array([3, 4, 5, 6, 7])

In [3]:
a-2 # Substracting 2 to each element

array([-1,  0,  1,  2,  3])

In [4]:
a*2 # Multiplying 2 to each element

array([ 2,  4,  6,  8, 10])

In [5]:
a/2 # Dividing 2 to each element

array([0.5, 1. , 1.5, 2. , 2.5])

In [6]:
a//2 # Integer Dividing 2 to each element

array([0, 1, 1, 2, 2])

In [7]:
a**2 # Powering 2 to each element

array([ 1,  4,  9, 16, 25])

In [8]:
a%2 # Modulus Dividing 2 to each element

array([1, 0, 1, 0, 1])

In [9]:
a/0 # Dividing 0 to each element, giving "inf" i.e. infinite as output

/var/folders/tl/hdrnf2y12_dfs7brk68x42yc0000gn/T/ipykernel_4828/1984730862.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0 # Dividing 0 to each element, giving "inf" i.e. infinite as output


array([inf, inf, inf, inf, inf])

In [10]:
b = np.arange(0, 5)
print("a =", a)
print("\nb =", b)

a = [1 2 3 4 5]

b = [0 1 2 3 4]


In [11]:
a+b # Addition of two arrays, elementwise addition

array([1, 3, 5, 7, 9])

In [12]:
a-b # Substraction of two arrays, elementwise substraction

array([1, 1, 1, 1, 1])

In [13]:
a*b # Multiplication of two arrays, elementwise multiplication

array([ 0,  2,  6, 12, 20])

In [14]:
a/b # Division of two arrays, elementwise division

/var/folders/tl/hdrnf2y12_dfs7brk68x42yc0000gn/T/ipykernel_4828/3578863175.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b # Division of two arrays, elementwise division


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ])

In [15]:
a**b # Powering of two arrays, elementwise powering

array([  1,   2,   9,  64, 625])

In [16]:
a%b # Modulus of two arrays, elementwise modulus, carefully look the output

/var/folders/tl/hdrnf2y12_dfs7brk68x42yc0000gn/T/ipykernel_4828/2372629425.py:1: RuntimeWarning: divide by zero encountered in remainder
  a%b # Modulus of two arrays, elementwise modulus, carefully look the output


array([0, 0, 1, 1, 1])

In [17]:
a//b # Integer Division of two arrays, elementwise integer division, look the output carefully

/var/folders/tl/hdrnf2y12_dfs7brk68x42yc0000gn/T/ipykernel_4828/1331603338.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a//b # Integer Division of two arrays, elementwise integer division, look the output carefully


array([0, 2, 1, 1, 1])

In [18]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
print("a =\n", a)
b = np.array([5, 6, 7, 8]).reshape(2, 2)
print("\nb =\n", b)

a =
 [[1 2]
 [3 4]]

b =
 [[5 6]
 [7 8]]


In [19]:
a*b # Elementwise multiplication

array([[ 5, 12],
       [21, 32]])

In [20]:
a.dot(b) # Matrix Multiplication i.e. ab

array([[19, 22],
       [43, 50]])