## Various Built-in Functions in NumPy
- There are many built-in functions in NumPy library.
- These functions have very less computational cost i.e. cost effective.

### For 1D Array

In [1]:
import numpy as np
np.random.seed(36)
a = np.random.randint(10, 99, 12)
a

array([15, 40, 50, 43, 54, 19, 47, 65, 16, 74, 80, 80])

In [2]:
np.sum(a) # Sum of all elements in the array

np.int64(583)

In [3]:
np.min(a) # Minimum element in the array

np.int64(15)

In [4]:
np.max(a) # Maximum element in the array

np.int64(80)

In [5]:
np.argmin(a) # Index of the minimum element in the array

np.int64(0)

In [6]:
np.argmax(a) # Index of the maximum element in the array

np.int64(10)

In [7]:
np.sqrt(a) # Square root of each element in the array

array([3.87298335, 6.32455532, 7.07106781, 6.55743852, 7.34846923,
       4.35889894, 6.8556546 , 8.06225775, 4.        , 8.60232527,
       8.94427191, 8.94427191])

In [8]:
np.sin(a) # Sine of each element in the array

array([ 0.65028784,  0.74511316, -0.26237485, -0.83177474, -0.55878905,
        0.14987721,  0.12357312,  0.82682868, -0.28790332, -0.98514626,
       -0.99388865, -0.99388865])

In [9]:
np.cos(a) # Cosine of each element in the array

array([-0.75968791, -0.66693806,  0.96496603,  0.5551133 , -0.82930983,
        0.98870462, -0.99233547, -0.56245385, -0.95765948,  0.17171734,
       -0.11038724, -0.11038724])

In [10]:
np.tan(a) # Tangent of each element in the array

array([-0.8559934 , -1.11721493, -0.27190061, -1.49838734,  0.6738001 ,
        0.15158947, -0.12452757, -1.47003826,  0.30063224, -5.73702254,
        9.00365495,  9.00365495])

In [11]:
b = np.linspace(1, 3, 6) # Returns a 6 length array starts with 1, ends with 3 of equidistance values
b

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [12]:
b = np.linspace(1, -1, 6) # Returns a 6 length array starts with 1, ends with -1 of equidistance values
b

array([ 1. ,  0.6,  0.2, -0.2, -0.6, -1. ])

### For 2D or nD Array

In [13]:
import numpy as np
np.random.seed(36)
a = np.random.randint(10, 99, 12).reshape(3, 4)
a

array([[15, 40, 50, 43],
       [54, 19, 47, 65],
       [16, 74, 80, 80]])

In [14]:
np.sum(a, axis = 0) # Sum of each column

array([ 85, 133, 177, 188])

In [15]:
np.sum(a, axis = 1) # Sum of each row

array([148, 185, 250])

In [16]:
np.cumsum(a) # Cumulative sum of each element

array([ 15,  55, 105, 148, 202, 221, 268, 333, 349, 423, 503, 583])

In [17]:
np.cumsum(a, axis = 0) # Cumulative sum of each column

array([[ 15,  40,  50,  43],
       [ 69,  59,  97, 108],
       [ 85, 133, 177, 188]])

In [18]:
np.cumsum(a, axis = 1) # Cumulative sum of each row

array([[ 15,  55, 105, 148],
       [ 54,  73, 120, 185],
       [ 16,  90, 170, 250]])

In [19]:
np.min(a, axis = 0) # Minimum of each column

array([15, 19, 47, 43])

In [20]:
np.max(a, axis = 1) # Maximum of each row

array([50, 65, 80])

In [21]:
c = np.random.randint(10, 99, 24).reshape(2, 3, 4)
c

array([[[32, 41, 11, 32],
        [46, 24, 93, 87],
        [40, 55, 31, 23]],

       [[47, 32, 56, 35],
        [77, 34, 51, 74],
        [84, 88, 29, 98]]])

In [22]:
c.shape

(2, 3, 4)

In [23]:
np.mean(c, axis = 0) # Mean of each axis = 0 (2)

array([[39.5, 36.5, 33.5, 33.5],
       [61.5, 29. , 72. , 80.5],
       [62. , 71.5, 30. , 60.5]])

In [24]:
np.median(c, axis = 1) # Median of each axis = 1 (3)

array([[40., 41., 31., 32.],
       [77., 34., 51., 74.]])

In [25]:
np.sum(c, axis = 2) # Sum of each axis = 2 (4)

array([[116, 250, 149],
       [170, 236, 299]])

In [26]:
np.random.shuffle(c) # Shuffling the array
c

array([[[47, 32, 56, 35],
        [77, 34, 51, 74],
        [84, 88, 29, 98]],

       [[32, 41, 11, 32],
        [46, 24, 93, 87],
        [40, 55, 31, 23]]])

In [27]:
np.unique(a, axis = 1) # Rowise unique elements in the array

array([[15, 40, 43, 50],
       [54, 19, 65, 47],
       [16, 74, 80, 80]])

In [28]:
np.unique(c, axis = 0) # Unique elements in the array of axis = 0 (2)

array([[[32, 41, 11, 32],
        [46, 24, 93, 87],
        [40, 55, 31, 23]],

       [[47, 32, 56, 35],
        [77, 34, 51, 74],
        [84, 88, 29, 98]]])

In [29]:
np.unique(c).size # Total number of unique elements in the array

22

In [30]:
print("a =\n", a, "\n")
np.unique(a, return_index = True, return_counts = True) # Unique elements, their index and their count

a =
 [[15 40 50 43]
 [54 19 47 65]
 [16 74 80 80]] 



(array([15, 16, 19, 40, 43, 47, 50, 54, 65, 74, 80]),
 array([ 0,  8,  5,  1,  3,  6,  2,  4,  7,  9, 10]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]))