## Stacking in NumPy Arrays
- There are mainly two types of stacking in 2D array, i.e. vertical stacking and horizontal stacking.

In [1]:
import numpy as np
np.random.seed(22)
a = np.random.randint(0, 5, 4)
b = np.random.randint(5, 10, 4)
print("a =", a)
print("\nb =", b)

a = [4 4 0 4]

b = [8 9 5 9]


In [2]:
np.hstack((a, b)) # Horizontal stacking of a and b

array([4, 4, 0, 4, 8, 9, 5, 9])

In [3]:
np.vstack((a, b)) # Vertical stacking of a and b

array([[4, 4, 0, 4],
       [8, 9, 5, 9]])

In [4]:
np.random.seed(22)
a = np.random.randint(0, 5, (3, 4))
b = np.random.randint(5, 10, (3, 4))
print("a =", a)
print("\nb =", b)

a = [[4 4 0 4]
 [3 4 0 4]
 [2 4 0 2]]

b = [[7 6 5 5]
 [8 9 7 7]
 [6 6 8 8]]


In [5]:
np.hstack((a, b)) # Horizontal stacking of a and b

array([[4, 4, 0, 4, 7, 6, 5, 5],
       [3, 4, 0, 4, 8, 9, 7, 7],
       [2, 4, 0, 2, 6, 6, 8, 8]])

In [6]:
np.vstack((a, b)) # Vertical stacking of a and b

array([[4, 4, 0, 4],
       [3, 4, 0, 4],
       [2, 4, 0, 2],
       [7, 6, 5, 5],
       [8, 9, 7, 7],
       [6, 6, 8, 8]])