<a href="https://colab.research.google.com/github/Sourish168/Python/blob/main/NumPy/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Searching and Inserting an Element in NumPy Array
- After finding the value in the array the function returns the index of the value in the array.
- For this inserting method the array should be sorted. Since it performs a Binary search to the array and then inserts the element.

In [1]:
import numpy as np
np.random.seed(24)
a = np.random.randint(0, 10, 12)
np.random.shuffle(a)
a

array([1, 1, 4, 2, 1, 3, 3, 2, 0, 3, 4, 7])

In [2]:
x = np.where(a == 3) # Returns the index of the value
x

(array([5, 6, 9]),)

In [3]:
a[x] # Returns the value of the index

array([3, 3, 3])

In [4]:
a = a.reshape((2, 3, 2))
a

array([[[1, 1],
        [4, 2],
        [1, 3]],

       [[3, 2],
        [0, 3],
        [4, 7]]])

In [5]:
x = np.where(a == 4) # Returns the index of the value
x

(array([0, 1]), array([1, 2]), array([0, 0]))

In [6]:
a[x] # Returns the value of the index

array([4, 4])

In [7]:
b = np.arange(1, 9)
evens = np.where(b%2 == 0) # Returns the index of the value
evens

(array([1, 3, 5, 7]),)

In [8]:
b[evens] # Returns the value of the index

array([2, 4, 6, 8])

In [9]:
np.random.seed(16)
c = np.random.randint(0, 10, 8)
c.sort() # We always have to sort it, else it give us a baseless output
c

array([0, 1, 4, 4, 5, 9, 9, 9])

In [10]:
x = 7
np.searchsorted(c, x) # Returns the index of the value

np.int64(5)

In [11]:
np.insert(c, np.searchsorted(c, x), x) # Inserts the value at the given index
c

array([0, 1, 4, 4, 5, 9, 9, 9])