<a href="https://colab.research.google.com/github/Sourish168/Python/blob/main/NumPy/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy
- <B>NumPy = Num(Numerical) + Py(Python)</B>
- Mainly use for Mathematical and Logical calculations on arrays(Vector, Matrix, Tensor, n-dimensional array etc).
- NumPy arrays are much more faster than Python Lists. Some reasons for this are "Array is a collection of similar types of data", NumPy is associated with C Programming etc.
- There are many built-in functions for Linear Algebra and many more scientific calculations in NumPy.
- For using all library functions of NumPy we can use the documentation: https://numpy.org/doc/stable/user/basics.html

## Importing NumPy Library

In [ ]:
!pip install numpy # Installing NumPy Library (Only for Jupyter Command Line)

In [ ]:
import numpy as np # Importing NumPy Library for using
# Using this command we can use "np" in place of "numpy"

## Executing Programs in NumPy
- There are 2 modes in a Jupyter Notebook cell <B>(i)Command Mode</B> and <B> (ii)Edit Mode.</B>
- We can write a code in a cell only in edit mode and after running the code it is in command mode.
- We can use <B><I><U>HTML Tags for our markdown cell.</B></I></U>

In [ ]:
import numpy as np
a = [1, 2, 3, 5]
a

[1, 2, 3, 5]

## Creating an Array using NumPy
- Using NumPy we can create n-dimensional arrays.
- We can input the values of the array from the user and make the numpy array.

In [ ]:
import numpy as np
a = [1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = []
n = int(input("Enter the size of an array: "))
for i in range(n):
    val = int(input(f"Enter input number {i+1}: "))
    a.append(val)
arr = np.array(a)
print("\nThe created array is:", arr)

Enter the size of an array: 5
Enter input number 1: 6
Enter input number 2: 11
Enter input number 3: 5
Enter input number 4: 2
Enter input number 5: 9

The created array is: [ 6 11  5  2  9]


## Creating Higher Dimensional Arrays using NumPy

In [ ]:
import numpy as np
a = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim # Checking the dimension of the array

2

In [ ]:
arr.shape # Checking the shape of the array

(3, 3)

## NumPy Built-in Functions
- Special Functions, that can easily implemented by NumPy.
- E.g. numpy.zeros, numpy.ones, numpy.eye etc.

In [1]:
import numpy as np
a = np.zeros(4) # Creating an one dimensional array of zeros
b = np.zeros((3, 4)) # Creating a two dimensional array of zeros
c = np.zeros((3, 4, 2)) # Creating a three dimensional array of zeros
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [0. 0. 0. 0.]

Array b:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array c:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [2]:
a = np.ones(4) # Creating an one dimensional array of ones
b = np.ones((3, 4)) # Creating a two dimensional array of ones
c = np.ones((3, 4, 2)) # Creating a three dimensional array of ones
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [1. 1. 1. 1.]

Array b:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array c:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [3]:
a = np.eye(3) # Creating an identity matrix
b = np.eye(3, 4) # Creating a matrix with ones on the diagonal
c = np.eye(3, 4, 1) # Creating a matrix with ones on the diagonal with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array b:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Array c:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
a = np.diag([1, 2, 3, 4]) # Creating a diagonal matrix
b = np.diag(a) # Extracting the diagonal elements of a matrix
c = np.diag(a, 1) # Extracting the diagonal elements of a matrix with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Array b:
 [1 2 3 4]

Array c:
 [0 0 0]


In [12]:
a = np.random.randint(1, 10, 3) # Creating an array of random integers
print("Array a:\n", a) # Generating 3 random integers from [1, 10)
b = np.random.randint(1, 10, (3, 4)) # Creating a 2D array of random integers
print("\nArray b:\n", b) # Generating 3x4 random integers from [1, 10)

Array a:
 [7 4 1]

Array b:
 [[1 5 8 1]
 [3 9 3 7]
 [4 6 7 8]]


In [13]:
a = np.random.rand(5) # Creating an array of random floats
print("Array a:\n", a) # Generating 5 random floats from [0, 1)
b = np.random.rand(2, 3) # Creating a 2D array of random floats
print("\nArray b:\n", b) # Generating 2x3 random floats from [0, 1)

Array a:
 [0.55277799 0.5176199  0.40930526 0.72178699 0.76080423]

Array b:
 [[0.48978169 0.25775549 0.58591398]
 [0.46457312 0.56777098 0.24875954]]


In [14]:
a = np.random.randn(5) # Creating an array of random floats from Normal Distribution
print("Array a:\n", a) # Generating 5 random floats from N(0, 1)
b = np.random.randn(2, 3) # Creating a 2D array of random floats from Normal Distribution
print("\nArray b:\n", b) # Generating 2x3 random floats from N(0, 1)

Array a:
 [ 1.36204427  0.04571876 -1.57136699 -0.83153114  0.77537055]

Array b:
 [[-0.81121094  0.9561041  -0.57351008]
 [ 0.12873472  1.83902549  0.13402432]]
