<a href="https://colab.research.google.com/github/Sourish168/Python/blob/main/NumPy/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy
- <B>NumPy = Num(Numerical) + Py(Python)</B>
- Mainly use for Mathematical and Logical calculations on arrays(Vector, Matrix, Tensor, n-dimensional array etc).
- NumPy arrays are much more faster than Python Lists. Some reasons for this are "Array is a collection of similar types of data", NumPy is associated with C Programming etc.
- There are many built-in functions for Linear Algebra and many more scientific calculations in NumPy.
- For using all library functions of NumPy we can use the documentation: https://numpy.org/doc/stable/user/basics.html

## Importing NumPy Library

In [ ]:
!pip install numpy # Installing NumPy Library (Only for Jupyter Command Line)

In [ ]:
import numpy as np # Importing NumPy Library for using
# Using this command we can use "np" in place of "numpy"

## Executing Programs in NumPy
- There are 2 modes in a Jupyter Notebook cell <B>(i)Command Mode</B> and <B> (ii)Edit Mode.</B>
- We can write a code in a cell only in edit mode and after running the code it is in command mode.
- We can use <B><I><U>HTML Tags for our markdown cell.</B></I></U>

In [ ]:
import numpy as np
a = [1, 2, 3, 5]
a

[1, 2, 3, 5]

## Creating an Array using NumPy
- Using NumPy we can create n-dimensional arrays.
- We can input the values of the array from the user and make the numpy array.

In [ ]:
import numpy as np
a = [1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = []
n = int(input("Enter the size of an array: "))
for i in range(n):
    val = int(input(f"Enter input number {i+1}: "))
    a.append(val)
arr = np.array(a)
print("\nThe created array is:", arr)

Enter the size of an array: 5
Enter input number 1: 6
Enter input number 2: 11
Enter input number 3: 5
Enter input number 4: 2
Enter input number 5: 9

The created array is: [ 6 11  5  2  9]


## Creating Higher Dimensional Arrays using NumPy

In [ ]:
import numpy as np
a = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim # Checking the dimension of the array

2

In [ ]:
arr.shape # Checking the shape of the array

(3, 3)

## NumPy Built-in Functions
- Special Functions, that can easily implemented by NumPy.
- E.g. numpy.zeros, numpy.ones, numpy.eye, numpy.random etc.

In [1]:
import numpy as np
a = np.zeros(4) # Creating an one dimensional array of zeros
b = np.zeros((3, 4)) # Creating a two dimensional array of zeros
c = np.zeros((3, 4, 2)) # Creating a three dimensional array of zeros
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [0. 0. 0. 0.]

Array b:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array c:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [2]:
a = np.ones(4) # Creating an one dimensional array of ones
b = np.ones((3, 4)) # Creating a two dimensional array of ones
c = np.ones((3, 4, 2)) # Creating a three dimensional array of ones
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [1. 1. 1. 1.]

Array b:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array c:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [3]:
a = np.eye(3) # Creating an identity matrix
b = np.eye(3, 4) # Creating a matrix with ones on the diagonal
c = np.eye(3, 4, 1) # Creating a matrix with ones on the diagonal with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array b:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Array c:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
a = np.diag([1, 2, 3, 4]) # Creating a diagonal matrix
b = np.diag(a) # Extracting the diagonal elements of a matrix
c = np.diag(a, 1) # Extracting the diagonal elements of a matrix with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Array b:
 [1 2 3 4]

Array c:
 [0 0 0]


In [12]:
a = np.random.randint(1, 10, 3) # Creating an array of random integers
print("Array a:\n", a) # Generating 3 random integers from [1, 10)
b = np.random.randint(1, 10, (3, 4)) # Creating a 2D array of random integers
print("\nArray b:\n", b) # Generating 3x4 random integers from [1, 10)

Array a:
 [7 4 1]

Array b:
 [[1 5 8 1]
 [3 9 3 7]
 [4 6 7 8]]


In [13]:
a = np.random.rand(5) # Creating an array of random floats
print("Array a:\n", a) # Generating 5 random floats from [0, 1)
b = np.random.rand(2, 3) # Creating a 2D array of random floats
print("\nArray b:\n", b) # Generating 2x3 random floats from [0, 1)

Array a:
 [0.55277799 0.5176199  0.40930526 0.72178699 0.76080423]

Array b:
 [[0.48978169 0.25775549 0.58591398]
 [0.46457312 0.56777098 0.24875954]]


In [14]:
a = np.random.randn(5) # Creating an array of random floats from Normal Distribution
print("Array a:\n", a) # Generating 5 random floats from N(0, 1)
b = np.random.randn(2, 3) # Creating a 2D array of random floats from Normal Distribution
print("\nArray b:\n", b) # Generating 2x3 random floats from N(0, 1)

Array a:
 [ 1.36204427  0.04571876 -1.57136699 -0.83153114  0.77537055]

Array b:
 [[-0.81121094  0.9561041  -0.57351008]
 [ 0.12873472  1.83902549  0.13402432]]


## Indexing & Slicing of NumPy Array
- To get any values from a NumPy array we can use indexing and slicing method.
- Always remember indexing in python starts from 0 upto n-1, where n = lenth of the array.
- For a n-dimensional array, we have to mention n different indexes, not more than that.
- In some cases less number of indexing by default considers the first m indexes of the array (m<n).
- We can use negetive indexing and slicing. Rule: index(n-k) = index(-k)

In [6]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"The {i} indexed element is:", a[i]) # 1D array indexing

Array a:
 [1 2 3 4 5 6 7 8 9] 

The 0 indexed element is: 1
The 1 indexed element is: 2
The 2 indexed element is: 3
The 3 indexed element is: 4
The 4 indexed element is: 5
The 5 indexed element is: 6
The 6 indexed element is: 7
The 7 indexed element is: 8
The 8 indexed element is: 9


In [12]:
a = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]]) # 2D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"The {i} indexed element is:", a[i]) # 1D array indexing but for each index it is giving a 1D array

Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

The 0 indexed element is: [1 2 3]
The 1 indexed element is: [4 5 6]
The 2 indexed element is: [7 8 9]


In [19]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"\nThe {i} indexed element is:\n", a[i]) # 1D array indexing but for each index it is giving a 2D array

for i in range(len(a)):
    for j in range(len(a[i])):
        print(f"\nThe ({i}, {j}) indexed element is:\n", a[i][j]) # 2D array indexing but for each index it is giving a 1D array

Array a:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] 


The 0 indexed element is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

The 1 indexed element is:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

The 2 indexed element is:
 [[21 22 23]
 [24 25 26]
 [27 28 29]]

The (0,0) indexed element is:
 [1 2 3]

The (0,1) indexed element is:
 [4 5 6]

The (0,2) indexed element is:
 [7 8 9]

The (1,0) indexed element is:
 [11 12 13]

The (1,1) indexed element is:
 [14 15 16]

The (1,2) indexed element is:
 [17 18 19]

The (2,0) indexed element is:
 [21 22 23]

The (2,1) indexed element is:
 [24 25 26]

The (2,2) indexed element is:
 [27 28 29]


In [24]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

print("The (0, 1, 2) indexed element of a is:", a[0, 1, 2]) # Indexing a 3D array
print("The (2, 1, 0) indexed element of a is:", a[2, 1, 0]) # Indexing a 3D array

print(a[1, 0, 2] == a[1][0][2]) # Checking if both are same, another way of indexing
print(a[1, 0] == a[1][0]) # Checking if both are same, another way of indexing
print(a[1] == a[1][0][2]) # Checking if both are same, another way of indexing
# For the 2nd and 3rd case it is checking element wise equality for both the arrays

The (0, 1, 2) indexed element of a is: 6
The (2, 1, 0) indexed element of a is: 24
True
[ True  True  True]
[[False False  True]
 [False False False]
 [False False False]]


In [30]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1D array
print("The slicing of b from 3rd index to 7th index is:", b[3:8])
print("\nThe slicing of a from 3rd index to 7th index is:\n", a[3:8]) # Since the index are empty
print("\nThe slicing of b from 0th index to 2nd index is:\n", a[0:2])

The slicing of b from 3rd index to 7th index is: [4 5 6 7 8]

The slicing of a from 3rd index to 7th index is:
 []

The slicing of b from 0th index to 2nd index is:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [88]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
print("a[1:] =\n", a[1:]) # Returns every element after and including 1
print("\na[:2] =\n", a[:2]) # Returns every element before 2 (excluding 2)
print("\na[1:, 1:] =\n", a[1:, 1:]) # Returns every element after and including [1, 1]
print("\na[:2, :2] =\n", a[:2, :2]) # Returns every element before [2, 2] (excluding [2, 2])

a[1:] =
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

a[:2] =
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

a[1:, 1:] =
 [[[14 15 16]
  [17 18 19]]

 [[24 25 26]
  [27 28 29]]]

a[:2, :2] =
 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [36]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

a[0:2, -1] == a[0:2, 2] # Checking if both are same, index(n-k) = index(-k), here k=1, n=3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [51]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

print("a[0:2] =\n", a[0:2])
print("\na[1:3] =\n", a[1:3])
print("\nSum of the above array slices is:\n", a[0:2]+a[1:3])
print("\nLet's divide the array sum by 2:\n", (a[0:2]+a[1:3])/2) # Note there is float value now
print("\nLet's divide the array sum by 8:\n", (a[0:2]+a[1:3])/8) # The float is clear now
print("\nLet's now convert the final array into integer array:")
np.array((a[0:2]+a[1:3])/8, dtype = np.int64)

a[0:2] =
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

a[1:3] =
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

Sum of the above array slices is:
 [[[12 14 16]
  [18 20 22]
  [24 26 28]]

 [[32 34 36]
  [38 40 42]
  [44 46 48]]]

Let's divide the array sum by 2:
 [[[ 6.  7.  8.]
  [ 9. 10. 11.]
  [12. 13. 14.]]

 [[16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]]]

Let's divide the array sum by 8:
 [[[1.5  1.75 2.  ]
  [2.25 2.5  2.75]
  [3.   3.25 3.5 ]]

 [[4.   4.25 4.5 ]
  [4.75 5.   5.25]
  [5.5  5.75 6.  ]]]

Let's now convert the final array into integer array:


array([[[1, 1, 2],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 5, 5],
        [5, 5, 6]]])

## Reshaping of Array
- We can reshape an array as required.
- But always remember that original array shape and reshaping array shape should be matching, or there is an error.

In [52]:
import numpy as np
a = np.random.randint(0, 99, (4, 3))
a

array([[65, 48, 21],
       [29, 30, 98],
       [17, 18, 31],
       [60, 67, 81]])

In [53]:
a.shape # Total 12 elements are there

(4, 3)

In [54]:
a.reshape(2, 6) # 2 rows and 6 columns, 12 elements

array([[65, 48, 21, 29, 30, 98],
       [17, 18, 31, 60, 67, 81]])

In [58]:
a.reshape(3, 4) # 3 rows and 4 columns, 12 elements

array([[65, 48, 21, 29],
       [30, 98, 17, 18],
       [31, 60, 67, 81]])

In [59]:
a.reshape(2, 3, 2) # 3D array

array([[[65, 48],
        [21, 29],
        [30, 98]],

       [[17, 18],
        [31, 60],
        [67, 81]]])

In [61]:
a.reshape(2, 1, 2, 3) # 4D array

array([[[[65, 48, 21],
         [29, 30, 98]]],


       [[[17, 18, 31],
         [60, 67, 81]]]])

In [62]:
a.reshape(1, 12) # 2D array

array([[65, 48, 21, 29, 30, 98, 17, 18, 31, 60, 67, 81]])

In [63]:
a.reshape(12) # 1D array

array([65, 48, 21, 29, 30, 98, 17, 18, 31, 60, 67, 81])

In [56]:
a.reshape(2, 7) # 2 rows and 7 columns, 14 elements, not 12 elements, gives error

ValueError: cannot reshape array of size 12 into shape (2,7)

In [55]:
a # The actual array is not changing

array([[65, 48, 21],
       [29, 30, 98],
       [17, 18, 31],
       [60, 67, 81]])

In [67]:
a = a.reshape(2, 2, 3) # To change the actual array
a

array([[[65, 48, 21],
        [29, 30, 98]],

       [[17, 18, 31],
        [60, 67, 81]]])

In [68]:
a.reshape(-1, 6) # Only assigning the column value

array([[65, 48, 21, 29, 30, 98],
       [17, 18, 31, 60, 67, 81]])

In [69]:
a.reshape(6, -1) # Only assigning the row value

array([[65, 48],
       [21, 29],
       [30, 98],
       [17, 18],
       [31, 60],
       [67, 81]])

In [70]:
a.reshape(2, 2, -1) # Only assigning the row and column

array([[[65, 48, 21],
        [29, 30, 98]],

       [[17, 18, 31],
        [60, 67, 81]]])

In [73]:
a.reshape(-4, 4) # Only assigning the column value

array([[65, 48, 21, 29],
       [30, 98, 17, 18],
       [31, 60, 67, 81]])

In [76]:
a.reshape(0, 12) # Since 0 cannot be a dimension

ValueError: cannot reshape array of size 12 into shape (0,12)

## NumPy Seed Function
- Used for many important purpose where we need to fix our randomly generated array.
- The pseudo number generator gives us the same output for a particular seed number.

In [83]:
import numpy as np
np.random.seed(10)
arr = np.random.randint(0, 100, 10)
arr # Seed always comes with Random number

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [84]:
np.random.seed(10)
arr = np.random.randint(0, 100, 10)
arr # Note the same random number is generated

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [85]:
np.random.seed(10)
arr = np.random.randint(0, 50, 10)
arr # Seed is same but the variation in range or dimension can change the array

array([ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29])

In [86]:
arr.size # Checking the size of the array

10

## NumPy Functions: View vs Copy

In [89]:
import numpy as np
