<a href="https://colab.research.google.com/github/Sourish168/Python/blob/main/NumPy/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy
- <B>NumPy = Num(Numerical) + Py(Python)</B>
- Mainly use for Mathematical and Logical calculations on arrays(Vector, Matrix, Tensor, n-dimensional array etc).
- NumPy arrays are much more faster than Python Lists. Some reasons for this are "Array is a collection of similar types of data", NumPy is associated with C Programming etc.
- There are many built-in functions for Linear Algebra and many more scientific calculations in NumPy.
- For using all library functions of NumPy we can use the documentation: https://numpy.org/doc/stable/user/basics.html

## Importing NumPy Library

In [1]:
!pip install numpy # Installing NumPy Library (Only for Jupyter Command Line)

In [2]:
import numpy as np # Importing NumPy Library for using
# Using this command we can use "np" in place of "numpy"

## Executing Programs in NumPy
- There are 2 modes in a Jupyter Notebook cell <B>(i)Command Mode</B> and <B> (ii)Edit Mode.</B>
- We can write a code in a cell only in edit mode and after running the code it is in command mode.
- We can use <B><I><U>HTML Tags for our markdown cell.</B></I></U>

In [3]:
import numpy as np
a = [1, 2, 3, 5]
a

[1, 2, 3, 5]

## Creating an Array using NumPy
- Using NumPy we can create n-dimensional arrays.
- We can input the values of the array from the user and make the numpy array.

In [4]:
import numpy as np
a = [1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [6]:
a = []
n = int(input("Enter the size of an array: "))
for i in range(n):
    val = int(input(f"Enter input number {i+1}: "))
    a.append(val)
arr = np.array(a)
print("\nThe created array is:", arr)

Enter the size of an array: 6
Enter input number 1: 14
Enter input number 2: 22
Enter input number 3: 16
Enter input number 4: 9
Enter input number 5: 3
Enter input number 6: 134

The created array is: [ 14  22  16   9   3 134]


## Creating Higher Dimensional Arrays using NumPy

In [7]:
import numpy as np
a = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.ndim # Checking the dimension of the array

2

In [9]:
arr.shape # Checking the shape of the array

(3, 3)

## NumPy Built-in Functions
- Special Functions, that can easily implemented by NumPy.
- E.g. numpy.zeros, numpy.ones, numpy.eye, numpy.random etc.

In [10]:
import numpy as np
a = np.zeros(4) # Creating an one dimensional array of zeros
b = np.zeros((3, 4)) # Creating a two dimensional array of zeros
c = np.zeros((3, 4, 2)) # Creating a three dimensional array of zeros
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [0. 0. 0. 0.]

Array b:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array c:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [11]:
a = np.ones(4) # Creating an one dimensional array of ones
b = np.ones((3, 4)) # Creating a two dimensional array of ones
c = np.ones((3, 4, 2)) # Creating a three dimensional array of ones
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [1. 1. 1. 1.]

Array b:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array c:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [12]:
a = np.eye(3) # Creating an identity matrix
b = np.eye(3, 4) # Creating a matrix with ones on the diagonal
c = np.eye(3, 4, 1) # Creating a matrix with ones on the diagonal with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array b:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

Array c:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
a = np.diag([1, 2, 3, 4]) # Creating a diagonal matrix
b = np.diag(a) # Extracting the diagonal elements of a matrix
c = np.diag(a, 1) # Extracting the diagonal elements of a matrix with a shift of 1
print("Array a:\n", a)
print("\nArray b:\n", b)
print("\nArray c:\n", c)

Array a:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Array b:
 [1 2 3 4]

Array c:
 [0 0 0]


In [14]:
a = np.random.randint(1, 10, 3) # Creating an array of random integers
print("Array a:\n", a) # Generating 3 random integers from [1, 10)
b = np.random.randint(1, 10, (3, 4)) # Creating a 2D array of random integers
print("\nArray b:\n", b) # Generating 3x4 random integers from [1, 10)

Array a:
 [8 6 8]

Array b:
 [[9 7 7 9]
 [1 5 9 5]
 [8 9 8 6]]


In [15]:
a = np.random.rand(5) # Creating an array of random floats
print("Array a:\n", a) # Generating 5 random floats from [0, 1)
b = np.random.rand(2, 3) # Creating a 2D array of random floats
print("\nArray b:\n", b) # Generating 2x3 random floats from [0, 1)

Array a:
 [0.66370314 0.26710126 0.02765466 0.4286807  0.19789998]

Array b:
 [[0.58734245 0.50733892 0.07531211]
 [0.16039443 0.25859461 0.82623417]]


In [16]:
a = np.random.randn(5) # Creating an array of random floats from Normal Distribution
print("Array a:\n", a) # Generating 5 random floats from N(0, 1)
b = np.random.randn(2, 3) # Creating a 2D array of random floats from Normal Distribution
print("\nArray b:\n", b) # Generating 2x3 random floats from N(0, 1)

Array a:
 [ 0.70608384 -0.12269648 -1.26892076  1.25446932  0.62411166]

Array b:
 [[ 0.21271688 -1.8809171  -0.01167222]
 [-1.78383246 -0.30532739  1.38706355]]


## Indexing & Slicing of NumPy Array
- To get any values from a NumPy array we can use indexing and slicing method.
- Always remember indexing in python starts from 0 upto n-1, where n = lenth of the array.
- For a n-dimensional array, we have to mention n different indexes, not more than that.
- In some cases less number of indexing by default considers the first m indexes of the array (m<n).
- We can use negetive indexing and slicing. Rule: index(n-k) = index(-k)

In [17]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"The {i} indexed element is:", a[i]) # 1D array indexing

Array a:
 [1 2 3 4 5 6 7 8 9] 

The 0 indexed element is: 1
The 1 indexed element is: 2
The 2 indexed element is: 3
The 3 indexed element is: 4
The 4 indexed element is: 5
The 5 indexed element is: 6
The 6 indexed element is: 7
The 7 indexed element is: 8
The 8 indexed element is: 9


In [18]:
a = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]]) # 2D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"The {i} indexed element is:", a[i]) # 1D array indexing but for each index it is giving a 1D array

Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

The 0 indexed element is: [1 2 3]
The 1 indexed element is: [4 5 6]
The 2 indexed element is: [7 8 9]


In [19]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
print("Array a:\n", a, "\n")

for i in range(len(a)):
    print(f"\nThe {i} indexed element is:\n", a[i]) # 1D array indexing but for each index it is giving a 2D array

for i in range(len(a)):
    for j in range(len(a[i])):
        print(f"\nThe ({i}, {j}) indexed element is:\n", a[i][j]) # 2D array indexing but for each index it is giving a 1D array

Array a:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]] 


The 0 indexed element is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

The 1 indexed element is:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

The 2 indexed element is:
 [[21 22 23]
 [24 25 26]
 [27 28 29]]

The (0, 0) indexed element is:
 [1 2 3]

The (0, 1) indexed element is:
 [4 5 6]

The (0, 2) indexed element is:
 [7 8 9]

The (1, 0) indexed element is:
 [11 12 13]

The (1, 1) indexed element is:
 [14 15 16]

The (1, 2) indexed element is:
 [17 18 19]

The (2, 0) indexed element is:
 [21 22 23]

The (2, 1) indexed element is:
 [24 25 26]

The (2, 2) indexed element is:
 [27 28 29]


In [20]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

print("The (0, 1, 2) indexed element of a is:", a[0, 1, 2]) # Indexing a 3D array
print("The (2, 1, 0) indexed element of a is:", a[2, 1, 0]) # Indexing a 3D array

print(a[1, 0, 2] == a[1][0][2]) # Checking if both are same, another way of indexing
print(a[1, 0] == a[1][0]) # Checking if both are same, another way of indexing
print(a[1] == a[1][0][2]) # Checking if both are same, another way of indexing
# For the 2nd and 3rd case it is checking element wise equality for both the arrays

The (0, 1, 2) indexed element of a is: 6
The (2, 1, 0) indexed element of a is: 24
True
[ True  True  True]
[[False False  True]
 [False False False]
 [False False False]]


In [21]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1D array
print("The slicing of b from 3rd index to 7th index is:", b[3:8])
print("\nThe slicing of a from 3rd index to 7th index is:\n", a[3:8]) # Since the index are empty
print("\nThe slicing of b from 0th index to 2nd index is:\n", a[0:2])

The slicing of b from 3rd index to 7th index is: [4 5 6 7 8]

The slicing of a from 3rd index to 7th index is:
 []

The slicing of b from 0th index to 2nd index is:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [22]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array
print("a[1:] =\n", a[1:]) # Returns every element after and including 1
print("\na[:2] =\n", a[:2]) # Returns every element before 2 (excluding 2)
print("\na[1:, 1:] =\n", a[1:, 1:]) # Returns every element after and including [1, 1]
print("\na[:2, :2] =\n", a[:2, :2]) # Returns every element before [2, 2] (excluding [2, 2])

a[1:] =
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

a[:2] =
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

a[1:, 1:] =
 [[[14 15 16]
  [17 18 19]]

 [[24 25 26]
  [27 28 29]]]

a[:2, :2] =
 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [23]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

a[0:2, -1] == a[0:2, 2] # Checking if both are same, index(n-k) = index(-k), here k=1, n=3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [24]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
              [[21, 22, 23], [24, 25, 26], [27, 28, 29]]]) # 3D array

print("a[0:2] =\n", a[0:2])
print("\na[1:3] =\n", a[1:3])
print("\nSum of the above array slices is:\n", a[0:2]+a[1:3])
print("\nLet's divide the array sum by 2:\n", (a[0:2]+a[1:3])/2) # Note there is float value now
print("\nLet's divide the array sum by 8:\n", (a[0:2]+a[1:3])/8) # The float is clear now
print("\nLet's now convert the final array into integer array:")
np.array((a[0:2]+a[1:3])/8, dtype = np.int64)

a[0:2] =
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

a[1:3] =
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]

Sum of the above array slices is:
 [[[12 14 16]
  [18 20 22]
  [24 26 28]]

 [[32 34 36]
  [38 40 42]
  [44 46 48]]]

Let's divide the array sum by 2:
 [[[ 6.  7.  8.]
  [ 9. 10. 11.]
  [12. 13. 14.]]

 [[16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]]]

Let's divide the array sum by 8:
 [[[1.5  1.75 2.  ]
  [2.25 2.5  2.75]
  [3.   3.25 3.5 ]]

 [[4.   4.25 4.5 ]
  [4.75 5.   5.25]
  [5.5  5.75 6.  ]]]

Let's now convert the final array into integer array:


array([[[1, 1, 2],
        [2, 2, 2],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 5, 5],
        [5, 5, 6]]])

## Reshaping of Array
- We can reshape an array as required.
- But always remember that original array shape and reshaping array shape should be matching, or there is an error.

In [25]:
import numpy as np
a = np.random.randint(0, 99, (4, 3))
a

array([[69, 91, 86],
       [50,  3, 55],
       [84, 40, 69],
       [91, 88, 81]])

In [26]:
a.shape # Total 12 elements are there

(4, 3)

In [27]:
a.reshape(2, 6) # 2 rows and 6 columns, 12 elements

array([[69, 91, 86, 50,  3, 55],
       [84, 40, 69, 91, 88, 81]])

In [28]:
a.reshape(3, 4) # 3 rows and 4 columns, 12 elements

array([[69, 91, 86, 50],
       [ 3, 55, 84, 40],
       [69, 91, 88, 81]])

In [29]:
a.reshape(2, 3, 2) # 3D array

array([[[69, 91],
        [86, 50],
        [ 3, 55]],

       [[84, 40],
        [69, 91],
        [88, 81]]])

In [30]:
a.reshape(2, 1, 2, 3) # 4D array

array([[[[69, 91, 86],
         [50,  3, 55]]],


       [[[84, 40, 69],
         [91, 88, 81]]]])

In [31]:
a.reshape(1, 12) # 2D array

array([[69, 91, 86, 50,  3, 55, 84, 40, 69, 91, 88, 81]])

In [32]:
a.reshape(12) # 1D array

array([69, 91, 86, 50,  3, 55, 84, 40, 69, 91, 88, 81])

In [34]:
a.reshape(2, 7) # 2 rows and 7 columns, 14 elements, not 12 elements, gives error

ValueError: cannot reshape array of size 12 into shape (2,7)

In [35]:
a # The actual array is not changing

array([[69, 91, 86],
       [50,  3, 55],
       [84, 40, 69],
       [91, 88, 81]])

In [36]:
a = a.reshape(2, 2, 3) # To change the actual array
a

array([[[69, 91, 86],
        [50,  3, 55]],

       [[84, 40, 69],
        [91, 88, 81]]])

In [37]:
a.reshape(-1, 6) # Only assigning the column value

array([[69, 91, 86, 50,  3, 55],
       [84, 40, 69, 91, 88, 81]])

In [38]:
a.reshape(6, -1) # Only assigning the row value

array([[69, 91],
       [86, 50],
       [ 3, 55],
       [84, 40],
       [69, 91],
       [88, 81]])

In [39]:
a.reshape(2, 2, -1) # Only assigning the row and column

array([[[69, 91, 86],
        [50,  3, 55]],

       [[84, 40, 69],
        [91, 88, 81]]])

In [40]:
a.reshape(-4, 4) # Only assigning the column value

array([[69, 91, 86, 50],
       [ 3, 55, 84, 40],
       [69, 91, 88, 81]])

In [42]:
a.reshape(0, 12) # Since 0 cannot be a dimension

ValueError: cannot reshape array of size 12 into shape (0,12)

## NumPy Seed Function
- Used for many important purpose where we need to fix our randomly generated array.
- The pseudo number generator gives us the same output for a particular seed number.

In [43]:
import numpy as np
np.random.seed(10)
arr = np.random.randint(0, 100, 10)
arr # Seed always comes with Random number

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [44]:
np.random.seed(10)
arr = np.random.randint(0, 100, 10)
arr # Note the same random number is generated

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [45]:
np.random.seed(10)
arr = np.random.randint(0, 50, 10)
arr # Seed is same but the variation in range or dimension can change the array

array([ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29])

In [46]:
arr.size # Checking the size of the array

10

## NumPy Functions: View vs Copy
- We can slice an array by two ways, making view or using a copy of it.
- <B>View:</B> In this method if we change any part of the subarray then it is replicated in original.
- <B>Copy:</B> In this method if we change any part of the subarray then it is not replicated in original.

In [47]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
b = a[4:7] # Slicing a subarray, by default it is using view technique
print("b =", b)
b[:] = 0
print("\nModified b =", b)
print("\nNote that, now a =", a)

b = [50 60 70]

Modified b = [0 0 0]

Note that, now a = [10 20 30 40  0  0  0 80]


In [48]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
b = a[4:7].copy() # Slicing a subarray, but this time using copy technique
print("b =", b)
b[:] = 0
print("\nModified b =", b)
print("\nNote that, now a =", a)

b = [50 60 70]

Modified b = [0 0 0]

Note that, now a = [10 20 30 40 50 60 70 80]


## Conditional Selection in NumPy Array
- We can use logical symbols for conditioning. E.g. logical or, logical and etc.
- We can update an array using conditional selection rule.

In [49]:
import numpy as np
a = np.arange(1, 15) # Arranging array elements starting from 1 to 14
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
a > 7 # Elementwise condition checking, creating binary array

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True])

In [51]:
a = np.arange(1, 15, 2) # Arranging array elements starting from 1 to 14 with gap 2
print("a =", a)
b = a >= 7 # Conditional selection
print("\nb =", b)
print("\na[b] =", a[b]) # Binary Indexing for retriving elements

a = [ 1  3  5  7  9 11 13]

b = [False False False  True  True  True  True]

a[b] = [ 7  9 11 13]


In [52]:
a = np.arange(0, 15)
print("a =", a, "\n")
a[a%2 == 0] # Conditional selection

a = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 



array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [53]:
print("a == 10:\n", a == 10, "\n") # == is logical equal
a[a == 10] # Conditional selection

a == 10:
 [False False False False False False False False False False  True False
 False False False] 



array([10])

In [54]:
print("(a > 5) & (a < 10):\n", (a > 5) & (a < 10), "\n") # & is logical and
a[(a > 5) & (a < 10)] # Conditional selection

(a > 5) & (a < 10):
 [False False False False False False  True  True  True  True False False
 False False False] 



array([6, 7, 8, 9])

In [55]:
print("(a < 5) & (a > 10):\n", (a < 5) & (a > 10), "\n")
a[(a < 5) & (a > 10)] # Conditional selection, everything is false, thus null array

(a < 5) & (a > 10):
 [False False False False False False False False False False False False
 False False False] 



array([], dtype=int64)

In [56]:
print("(a < 5) | (a > 10):\n", (a < 5) | (a > 10), "\n") # | is logical or
a[(a < 5) | (a > 10)] # Conditional selection

(a < 5) | (a > 10):
 [ True  True  True  True  True False False False False False False  True
  True  True  True] 



array([ 0,  1,  2,  3,  4, 11, 12, 13, 14])

In [57]:
a[a%2 == 0] = 0 # Conditional update
a # Replacing 0 for all True values

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0])

In [58]:
a = np.arange(1, 25).reshape(3, 4, 2)
a[(a%2 == 0) | (a%5 == 1)] = 0 # All even and 1, 11, 21 are in True position
a

array([[[ 0,  0],
        [ 3,  0],
        [ 5,  0],
        [ 7,  0]],

       [[ 9,  0],
        [ 0,  0],
        [13,  0],
        [15,  0]],

       [[17,  0],
        [19,  0],
        [ 0,  0],
        [23,  0]]])

## Various Operations on NumPy Array
- There are various operations in NumPy  array which are not our usual operations.

In [59]:
import numpy as np
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [60]:
a+2 # Adding 2 to each element

array([3, 4, 5, 6, 7])

In [61]:
a-2 # Substracting 2 to each element

array([-1,  0,  1,  2,  3])

In [62]:
a*2 # Multiplying 2 to each element

array([ 2,  4,  6,  8, 10])

In [63]:
a/2 # Dividing 2 to each element

array([0.5, 1. , 1.5, 2. , 2.5])

In [64]:
a//2 # Integer Dividing 2 to each element

array([0, 1, 1, 2, 2])

In [65]:
a**2 # Powering 2 to each element

array([ 1,  4,  9, 16, 25])

In [66]:
a%2 # Modulus Dividing 2 to each element

array([1, 0, 1, 0, 1])

In [67]:
a/0 # Dividing 0 to each element, giving "inf" i.e. infinite as output

<ipython-input-67-23fc9b5b92dd>:1: RuntimeWarning: divide by zero encountered in divide
  a/0 # Dividing 0 to each element, giving "inf" i.e. infinite as output


array([inf, inf, inf, inf, inf])

In [68]:
b = np.arange(0, 5)
print("a =", a)
print("\nb =", b)

a = [1 2 3 4 5]

b = [0 1 2 3 4]


In [69]:
a+b # Addition of two arrays, elementwise addition

array([1, 3, 5, 7, 9])

In [70]:
a-b # Substraction of two arrays, elementwise substraction

array([1, 1, 1, 1, 1])

In [71]:
a*b # Multiplication of two arrays, elementwise multiplication

array([ 0,  2,  6, 12, 20])

In [72]:
a/b # Division of two arrays, elementwise division

<ipython-input-72-c7ce1f903b76>:1: RuntimeWarning: divide by zero encountered in divide
  a/b # Division of two arrays, elementwise division


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ])

In [73]:
a**b # Powering of two arrays, elementwise powering

array([  1,   2,   9,  64, 625])

In [74]:
a%b # Modulus of two arrays, elementwise modulus, carefully look the output

<ipython-input-74-8c8a96040aed>:1: RuntimeWarning: divide by zero encountered in remainder
  a%b # Modulus of two arrays, elementwise modulus, carefully look the output


array([0, 0, 1, 1, 1])

In [75]:
a//b # Integer Division of two arrays, elementwise integer division, look the output carefully

<ipython-input-75-29a295f202ac>:1: RuntimeWarning: divide by zero encountered in floor_divide
  a//b # Integer Division of two arrays, elementwise integer division, look the output carefully


array([0, 2, 1, 1, 1])

In [76]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
print("a =\n", a)
b = np.array([5, 6, 7, 8]).reshape(2, 2)
print("\nb =\n", b)

a =
 [[1 2]
 [3 4]]

b =
 [[5 6]
 [7 8]]


In [77]:
a*b # Elementwise multiplication

array([[ 5, 12],
       [21, 32]])

In [78]:
a.dot(b) # Matrix Multiplication i.e. ab

array([[19, 22],
       [43, 50]])

## Various Built-in Functions in NumPy
- There are many built-in functions in NumPy library.
- These functions have very less computational cost i.e. cost effective.

### For 1D Array

In [79]:
import numpy as np
np.random.seed(36)
a = np.random.randint(10, 99, 12)
a

array([15, 40, 50, 43, 54, 19, 47, 65, 16, 74, 80, 80])

In [80]:
np.sum(a) # Sum of all elements in the array

583

In [81]:
np.min(a) # Minimum element in the array

15

In [82]:
np.max(a) # Maximum element in the array

80

In [83]:
np.argmin(a) # Index of the minimum element in the array

0

In [84]:
np.argmax(a) # Index of the maximum element in the array

10

In [85]:
np.sqrt(a) # Square root of each element in the array

array([3.87298335, 6.32455532, 7.07106781, 6.55743852, 7.34846923,
       4.35889894, 6.8556546 , 8.06225775, 4.        , 8.60232527,
       8.94427191, 8.94427191])

In [86]:
np.sin(a) # Sine of each element in the array

array([ 0.65028784,  0.74511316, -0.26237485, -0.83177474, -0.55878905,
        0.14987721,  0.12357312,  0.82682868, -0.28790332, -0.98514626,
       -0.99388865, -0.99388865])

In [87]:
np.cos(a) # Cosine of each element in the array

array([-0.75968791, -0.66693806,  0.96496603,  0.5551133 , -0.82930983,
        0.98870462, -0.99233547, -0.56245385, -0.95765948,  0.17171734,
       -0.11038724, -0.11038724])

In [88]:
np.tan(a) # Tangent of each element in the array

array([-0.8559934 , -1.11721493, -0.27190061, -1.49838734,  0.6738001 ,
        0.15158947, -0.12452757, -1.47003826,  0.30063224, -5.73702254,
        9.00365495,  9.00365495])

In [89]:
b = np.linspace(1, 3, 6) # Returns a 6 length array starts with 1, ends with 3 of equidistance values
b

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [90]:
b = np.linspace(1, -1, 6) # Returns a 6 length array starts with 1, ends with -1 of equidistance values
b

array([ 1. ,  0.6,  0.2, -0.2, -0.6, -1. ])

### For 2D or nD Array

In [91]:
import numpy as np
np.random.seed(36)
a = np.random.randint(10, 99, 12).reshape(3, 4)
a

array([[15, 40, 50, 43],
       [54, 19, 47, 65],
       [16, 74, 80, 80]])

In [92]:
np.sum(a, axis = 0) # Sum of each column

array([ 85, 133, 177, 188])

In [93]:
np.sum(a, axis = 1) # Sum of each row

array([148, 185, 250])

In [94]:
np.cumsum(a) # Cumulative sum of each element

array([ 15,  55, 105, 148, 202, 221, 268, 333, 349, 423, 503, 583])

In [95]:
np.cumsum(a, axis = 0) # Cumulative sum of each column

array([[ 15,  40,  50,  43],
       [ 69,  59,  97, 108],
       [ 85, 133, 177, 188]])

In [96]:
np.cumsum(a, axis = 1) # Cumulative sum of each row

array([[ 15,  55, 105, 148],
       [ 54,  73, 120, 185],
       [ 16,  90, 170, 250]])

In [97]:
np.min(a, axis = 0) # Minimum of each column

array([15, 19, 47, 43])

In [98]:
np.max(a, axis = 1) # Maximum of each row

array([50, 65, 80])

In [99]:
c = np.random.randint(10, 99, 24).reshape(2, 3, 4)
c

array([[[32, 41, 11, 32],
        [46, 24, 93, 87],
        [40, 55, 31, 23]],

       [[47, 32, 56, 35],
        [77, 34, 51, 74],
        [84, 88, 29, 98]]])

In [100]:
c.shape

(2, 3, 4)

In [101]:
np.mean(c, axis = 0) # Mean of each axis = 0 (2)

array([[39.5, 36.5, 33.5, 33.5],
       [61.5, 29. , 72. , 80.5],
       [62. , 71.5, 30. , 60.5]])

In [102]:
np.median(c, axis = 1) # Median of each axis = 1 (3)

array([[40., 41., 31., 32.],
       [77., 34., 51., 74.]])

In [103]:
np.sum(c, axis = 2) # Sum of each axis = 2 (4)

array([[116, 250, 149],
       [170, 236, 299]])

In [104]:
np.random.shuffle(c) # Shuffling the array
c

array([[[47, 32, 56, 35],
        [77, 34, 51, 74],
        [84, 88, 29, 98]],

       [[32, 41, 11, 32],
        [46, 24, 93, 87],
        [40, 55, 31, 23]]])

In [105]:
np.unique(a, axis = 1) # Rowise unique elements in the array

array([[15, 40, 43, 50],
       [54, 19, 65, 47],
       [16, 74, 80, 80]])

In [106]:
np.unique(c, axis = 0) # Unique elements in the array of axis = 0 (2)

array([[[32, 41, 11, 32],
        [46, 24, 93, 87],
        [40, 55, 31, 23]],

       [[47, 32, 56, 35],
        [77, 34, 51, 74],
        [84, 88, 29, 98]]])

In [107]:
np.unique(c).size # Total number of unique elements in the array

22

In [108]:
print("a =\n", a, "\n")
np.unique(a, return_index = True, return_counts = True) # Unique elements, their index and their count

a =
 [[15 40 50 43]
 [54 19 47 65]
 [16 74 80 80]] 



(array([15, 16, 19, 40, 43, 47, 50, 54, 65, 74, 80]),
 array([ 0,  8,  5,  1,  3,  6,  2,  4,  7,  9, 10]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]))

## Stacking in NumPy Arrays
- There are mainly two types of stacking in 2D array, i.e. vertical stacking and horizontal stacking.

In [109]:
import numpy as np
np.random.seed(22)
a = np.random.randint(0, 5, 4)
b = np.random.randint(5, 10, 4)
print("a =", a)
print("\nb =", b)

a = [4 4 0 4]

b = [8 9 5 9]


In [110]:
np.hstack((a, b)) # Horizontal stacking of a and b

array([4, 4, 0, 4, 8, 9, 5, 9])

In [111]:
np.vstack((a, b)) # Vertical stacking of a and b

array([[4, 4, 0, 4],
       [8, 9, 5, 9]])

In [112]:
np.random.seed(22)
a = np.random.randint(0, 5, (3, 4))
b = np.random.randint(5, 10, (3, 4))
print("a =", a)
print("\nb =", b)

a = [[4 4 0 4]
 [3 4 0 4]
 [2 4 0 2]]

b = [[7 6 5 5]
 [8 9 7 7]
 [6 6 8 8]]


In [113]:
np.hstack((a, b)) # Horizontal stacking of a and b

array([[4, 4, 0, 4, 7, 6, 5, 5],
       [3, 4, 0, 4, 8, 9, 7, 7],
       [2, 4, 0, 2, 6, 6, 8, 8]])

In [114]:
np.vstack((a, b)) # Vertical stacking of a and b

array([[4, 4, 0, 4],
       [3, 4, 0, 4],
       [2, 4, 0, 2],
       [7, 6, 5, 5],
       [8, 9, 7, 7],
       [6, 6, 8, 8]])

## NumPy Array vs Python List
- <B>Size:</B> NumPy data structure take up less space.
- <B>Performance:</B> NumPy arrays are faster than Python lists.
- <B>Functionality:</B> SciPy and NumPy have optimized built-in functions, such as linear algebra operations.

In [115]:
import numpy as np

In [116]:
%timeit [i**2 for i in range(1, 11)] # Python list
%timeit np.arange(1, 11)**2 # NumPy array

3.94 µs ± 651 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.53 µs ± 406 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [117]:
%%timeit
l = [] # Python list
for i in range(1, 100000):
    l.append(i**2)

44.7 ms ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [118]:
%%timeit
np.arange(1, 100000)**2 # NumPy array

114 µs ± 809 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Searching and Inserting an Element in NumPy Array
- After finding the value in the array the function returns the index of the value in the array.
- For this inserting method the array should be sorted. Since it performs a Binary search to the array and then inserts the element.

In [119]:
import numpy as np
np.random.seed(24)
a = np.random.randint(0, 10, 12)
np.random.shuffle(a)
a

array([1, 1, 4, 2, 1, 3, 3, 2, 0, 3, 4, 7])

In [120]:
x = np.where(a == 3) # Returns the index of the value
x

(array([5, 6, 9]),)

In [121]:
a[x] # Returns the value of the index

array([3, 3, 3])

In [122]:
a = a.reshape((2, 3, 2))
a

array([[[1, 1],
        [4, 2],
        [1, 3]],

       [[3, 2],
        [0, 3],
        [4, 7]]])

In [123]:
x = np.where(a == 4) # Returns the index of the value
x

(array([0, 1]), array([1, 2]), array([0, 0]))

In [124]:
a[x] # Returns the value of the index

array([4, 4])

In [125]:
b = np.arange(1, 9)
evens = np.where(b%2 == 0) # Returns the index of the value
evens

(array([1, 3, 5, 7]),)

In [126]:
b[evens] # Returns the value of the index

array([2, 4, 6, 8])

In [127]:
np.random.seed(16)
c = np.random.randint(0, 10, 8)
c.sort() # We always have to sort it, else it give us a baseless output
c

array([0, 1, 4, 4, 5, 9, 9, 9])

In [128]:
x = 7
np.searchsorted(c, x) # Returns the index of the value

5

In [129]:
np.insert(c, np.searchsorted(c, x), x) # Inserts the value at the given index
c

array([0, 1, 4, 4, 5, 9, 9, 9])